name: norm
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:

  # a.
  auto_route: ^5.0.2

  # b.

  # c.
  cached_network_image: ^3.2.0
  contacts_service: ^0.6.3
  connectivity_plus: ^2.3.0

  # d.
  device_info_plus: ^3.2.3
  dio: ^4.0.6
  dio_smart_retry: ^1.3.2

  # e.
  equatable: ^2.0.5
  extended_image:
    path: packages/extended_image

  # f.
  firebase_core: ^2.4.0
  firebase_messaging: ^14.2.0

  flutter:
    sdk: flutter

  flutter_keyboard_size: ^1.0.0+4
  flutter_image_compress: ^1.1.3
  flutter_mobx: ^2.0.4
  fluttertoast: ^8.0.9
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.0.3

  flutter_localizations:
    sdk: flutter

  # g.
  get_it: ^7.0.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.3
  google_maps_webservice:
    git: https://github.com/lejard-h/google_maps_webservice

  # h.
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # i.
  image: ^3.1.3
  image_picker: ^0.8.5
  intl: ^0.18.0
  isolator: ^2.0.3

  # j.
  json_annotation: ^4.4.0

  # p.
  package_info: ^2.0.2
  path_provider: ^2.0.11
  permission_handler: any
  provider: ^6.0.5
  pull_to_refresh: ^2.0.0

  # m.
  mobx: ^2.1.1
  modal_bottom_sheet: ^2.1.2

  # s.
  sentry_flutter: ^6.11.2
  scrollable_positioned_list: ^0.3.5
  smooth_page_indicator: ^1.0.0+2
  share_plus: ^4.5.0

  # u.
  url_launcher: ^6.0.20

  # v.
  vibration: ^1.7.3

dev_dependencies:
  auto_route_generator: ^5.0.2

  build_runner:

  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
 
  import_sorter: ^4.6.0
  json_serializable: ^6.1.4
  mobx_codegen: ^2.0.7+3

import_sorter:
  ignored_files:
    - /app.*.map.json/
    - /*.g.dart/
    - /*.mocks.dart/

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/country_codes/
    - assets/splash/
    - assets/images/
    - assets/karma/
    - assets/maps/
    - assets/icons/
    - assets/icons/flags/
    - assets/icons/contacts/
  
  fonts:
    - family: Golos
      fonts:
        - asset: fonts/Golos/Golos-Regular.ttf
          weight: 400
        - asset: fonts/Golos/Golos-Medium.ttf
          weight: 500
        - asset: fonts/Golos/Golos-Bold.ttf
          weight: 700
    - family: RFDewi
      fonts:
        - asset: fonts/RFDewi/RFDewi-Light.ttf
          weight: 300
        - asset: fonts/RFDewi/RFDewi-Regular.ttf
          weight: 400
        - asset: fonts/RFDewi/RFDewi-Semibold.ttf
          weight: 600
        - asset: fonts/RFDewi/RFDewi-Bold.ttf
          weight: 700      
        


  